title: System Is Error
description: A collection of write-ups and research on real-world cyber security.

header_pages:
  - index.md
  - about.md

footer: '&lt;EOF&gt;'

style: dark
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      is_post: true